mri = read_mri('/home/jan/matlab/mri/templateMRI.mnc');

cd /analyse/4/Project0030/source/4DprepstBehav1/
load grandavg_alphaBehav1;
statC.dimord  = 'pos';
statC         = rmfield(statC, 'dim');
statC.prob(statC.outside) = 1;
statB.dimord  = 'pos';
statB         = rmfield(statB, 'dim');
statB.prob(statC.outside) = 1;
statX.dimord  = 'pos';
statX         = rmfield(statX, 'dim');
statX.prob(statC.outside) = 1;
cfg.parameter = {'stat' 'prob' 'mask'};
cfg.downsample = 2;
ialpha        = sourceinterpolate(cfg, statC, mri);
ialphab       = sourceinterpolate(cfg, statB, mri);
ialphax       = sourceinterpolate(cfg, statX, mri);
load grandavg_betaBehav1;
statC.dimord  = 'pos';
statC         = rmfield(statC, 'dim');
statC.prob(statC.outside) = 1;
statB.dimord  = 'pos';
statB         = rmfield(statB, 'dim');
statB.prob(statC.outside) = 1;
statX.dimord  = 'pos';
statX         = rmfield(statX, 'dim');
statX.prob(statC.outside) = 1;
ibeta         = sourceinterpolate(cfg, statC, mri);
ibetab        = sourceinterpolate(cfg, statB, mri);
ibetax        = sourceinterpolate(cfg, statX, mri);
load grandavg_gamma1Behav1;
statC.dimord  = 'pos';
statC         = rmfield(statC, 'dim');
statC.prob(statC.outside) = 1;
statB.dimord  = 'pos';
statB         = rmfield(statB, 'dim');
statB.prob(statC.outside) = 1;
statX.dimord  = 'pos';
statX         = rmfield(statX, 'dim');
statX.prob(statC.outside) = 1;
igamma1       = sourceinterpolate(cfg, statC,mri);
igamma1b      = sourceinterpolate(cfg, statB,mri);
igamma1x      = sourceinterpolate(cfg, statX,mri);
load grandavg_gamma2Behav1;
statC.dimord  = 'pos';
statC         = rmfield(statC, 'dim');
statC.prob(statC.outside) = 1;
statB.dimord  = 'pos';
statB         = rmfield(statB, 'dim');
statB.prob(statC.outside) = 1;
statX.dimord  = 'pos';
statX         = rmfield(statX, 'dim');
statX.prob(statC.outside) = 1;
igamma2       = sourceinterpolate(cfg, statC,mri);
igamma2b      = sourceinterpolate(cfg, statB,mri);
igamma2x      = sourceinterpolate(cfg, statX,mri);

ialpha.prob(~ialpha.inside)=1;
ialphab.prob(~ialpha.inside)=1;
ialphax.prob(~ialpha.inside)=1;
ibeta.prob(~ialpha.inside)=1;
ibetab.prob(~ialpha.inside)=1;
ibetax.prob(~ialpha.inside)=1;
igamma1.prob(~ialpha.inside)=1;
igamma1b.prob(~ialpha.inside)=1;
igamma1x.prob(~ialpha.inside)=1;
igamma2.prob(~ialpha.inside)=1;
igamma2b.prob(~ialpha.inside)=1;
igamma2x.prob(~ialpha.inside)=1;

cd /analyse/4/Project0030/figures/sourcedata/prepstBehav1/
cfgp = [];
cfgp.method = 'slice';
cfgp.funparameter = 'stat';
cfgp.maskparameter = 'prob';
cfgp.opacitymap = 'rampdown';
cfgp.nslices = 16;
%cfgp.slicerange = [70 155];
cfgp.opacitylim = [0 0.2];
figure;sourceplot(cfgp,ialpha);
print(gcf,'-dpng','statsAlphaBehav1');
figure;sourceplot(cfgp,ialphab);
print(gcf,'-dpng','statsAlphaBehav1b');
figure;sourceplot(cfgp,ialphax);
print(gcf,'-dpng','statsAlphaBehav1x');
figure;sourceplot(cfgp,ibeta);
print(gcf,'-dpng','statsBetaBehav1');
figure;sourceplot(cfgp,ibetab);
print(gcf,'-dpng','statsBetaBehav1b');
figure;sourceplot(cfgp,ibetax);
print(gcf,'-dpng','statsBetaBehav1x');
figure;sourceplot(cfgp,igamma2);
print(gcf,'-dpng','statsGamma2Behav1');
figure;sourceplot(cfgp,igamma2b);
print(gcf,'-dpng','statsGamma2Behav1b');
figure;sourceplot(cfgp,igamma2x);
print(gcf,'-dpng','statsGamma2Behav1x');
figure;sourceplot(cfgp,igamma1);
print(gcf,'-dpng','statsGamma1Behav1');
figure;sourceplot(cfgp,igamma1b);
print(gcf,'-dpng','statsGamma1Behav1b');
figure;sourceplot(cfgp,igamma1x);
print(gcf,'-dpng','statsGamma1Behav1x');


cfgp.nslices = 16;
cfgp.slicerange = [45 155];
cfgp.maskparameter = 'stat2';
ialphaB.stat2 = abs(ialphaB.stat);
cfgp.opacitylim = [5 30];
figure;sourceplot(cfgp,ialphaB);
print(gcf,'-dpng','AlphaPstPre');
ibetaB.stat2 = abs(ibetaB.stat);
ibetaB.stat2(~ibetaB.inside) = 0;
figure;sourceplot(cfgp,ibetaB);
print(gcf,'-dpng','BetaPstPre');
igamma1B.stat2 = abs(igamma1B.stat);
figure;sourceplot(cfgp,ibeta);
print(gcf,'-dpng','statsBetaBehav1');
figure;sourceplot(cfgp,igamma2);
print(gcf,'-dpng','statsGamma2Behav1');
figure;sourceplot(cfgp,igamma1);
print(gcf,'-dpng','statsGamma1Behav1');


cfgp.nslices = 16;
cfgp.slicerange = [45 155];
cfgp.maskparameter = 'stat2';
ialphaB.stat2 = abs(ialphaB.stat);
cfgp.opacitylim = [5 30];
figure;sourceplot(cfgp,ialphaB);
print(gcf,'-dpng','AlphaPstPre');
ibetaB.stat2 = abs(ibetaB.stat);
ibetaB.stat2(~ibetaB.inside) = 0;
figure;sourceplot(cfgp,ibetaB);
print(gcf,'-dpng','BetaPstPre');
igamma1B.stat2 = abs(igamma1B.stat);
figure;sourceplot(cfgp,ibeta);
print(gcf,'-dpng','statsBetaBehav1');
figure;sourceplot(cfgp,igamma2);
print(gcf,'-dpng','statsGamma2Behav1');
figure;sourceplot(cfgp,igamma1);
print(gcf,'-dpng','statsGamma1Behav1');


cfgp.nslices = 16;
cfgp.slicerange = [45 155];
cfgp.maskparameter = 'stat2';
ialphaB.stat2 = abs(ialphaB.stat);
cfgp.opacitylim = [5 30];
figure;sourceplot(cfgp,ialphaB);
print(gcf,'-dpng','AlphaPstPre');
ibetaB.stat2 = abs(ibetaB.stat);
ibetaB.stat2(~ibetaB.inside) = 0;
figure;sourceplot(cfgp,ibetaB);
print(gcf,'-dpng','BetaPstPre');
igamma1B.stat2 = abs(igamma1B.stat);
cfgp.opacitylim = [3 15];
figure;sourceplot(cfgp,igamma1B);
print(gcf,'-dpng','Gamma1PstPre');
igamma2B.stat2 = abs(igamma2B.stat);
cfgp.opacitylim = [10 20]
figure;sourceplot(cfgp,igamma2B);
print(gcf,'-dpng','Gamma2PstPre');

cfgp2 = [];
cfgp2.method = 'ortho';
cfgp2.interactive = 'yes';
cfgp2.funparameter = 'stat';
cfgp2.maskparameter = 'mask';
cfgp2.opacitylim = [0.5 1.2];
cfgp2.atlas      = '/home/jan/matlab/fieldtrip/TTatlas+tlrc.BRIK';
cfgp2.inputcoord = 'mni';
figure;sourceplot(cfgp2,ialpha);
